/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS2 Foundations',
      collapsible: true,
      collapsed: false,
      items: [
        'modules/01-ros2/00-overview',
        'modules/01-ros2/04-first-ros2-humanoid-package',
        'modules/01-ros2/05-urdf-xacro-mastery',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Environments',
      collapsible: true,
      collapsed: true,
      items: [
        'modules/02-simulation/00-overview',
        'modules/02-simulation/06-gazebo-ignition-deep-dive',
        'modules/02-simulation/07-unity-robotics-hub',
        'modules/02-simulation/08-indoor-environments-sensor-noise',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Sim',
      collapsible: true,
      collapsed: true,
      items: [
        'modules/03-isaac/00-overview',
        'modules/03-isaac/09-isaac-sim-deep-dive',
        'modules/03-isaac/10-isaac-ros-jetson',
        'modules/03-isaac/11-bipedal-locomotion-whole-body-control',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      collapsible: true,
      collapsed: true,
      items: [
        'modules/04-vla/00-overview',
        'modules/04-vla/12-vision-language-action-models',
        'modules/04-vla/13-voice-to-action',
        'modules/04-vla/14-llm-to-ros2-translation',
        'modules/04-vla/15-capstone-full-autonomous-humanoid',
      ],
    },
    {
      type: 'category',
      label: 'Conclusion',
      collapsible: true,
      collapsed: true,
      items: [
        'conclusion/16-sim-to-real-deployment',
        'conclusion/17-future-household-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      collapsible: true,
      collapsed: true,
      items: [
        'appendices/appendix-a-hardware-guide',
        'appendices/appendix-b-jetson-student-kit',
        'appendices/appendix-c-cloud-on-prem-costs',
        'appendices/appendix-d-prompt-history',
      ],
    },
  ],
};

module.exports = sidebars;